// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRs6efaAmYQgxvos2iT-12SJs5PyATI5k',
    appId: '1:613683440998:web:29839912f2393e8443aca7',
    messagingSenderId: '613683440998',
    projectId: 'fincom-dec4a',
    authDomain: 'fincom-dec4a.firebaseapp.com',
    storageBucket: 'fincom-dec4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZM3m0j6lq9l_TN1YEufVDcRgyMHXaIqw',
    appId: '1:613683440998:android:ea6c20c6f0f2d64443aca7',
    messagingSenderId: '613683440998',
    projectId: 'fincom-dec4a',
    storageBucket: 'fincom-dec4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWHYXOf66jaidtI-ZMi-VInu60iF8yk8',
    appId: '1:613683440998:ios:3ef8400972ba06a843aca7',
    messagingSenderId: '613683440998',
    projectId: 'fincom-dec4a',
    storageBucket: 'fincom-dec4a.firebasestorage.app',
    androidClientId: '613683440998-n6ctlkdlpldg2cg4sol3eqnihgbmp1og.apps.googleusercontent.com',
    iosClientId: '613683440998-mflo4osd0na886a7oedl75hq7srm5df8.apps.googleusercontent.com',
    iosBundleId: 'com.accounts.ara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWHYXOf66jaidtI-ZMi-VInu60iF8yk8',
    appId: '1:613683440998:ios:e3c308e2bd928a1243aca7',
    messagingSenderId: '613683440998',
    projectId: 'fincom-dec4a',
    storageBucket: 'fincom-dec4a.firebasestorage.app',
    androidClientId: '613683440998-n6ctlkdlpldg2cg4sol3eqnihgbmp1og.apps.googleusercontent.com',
    iosClientId: '613683440998-fgkvvrngej4juso1781a4oi1gpt8h28u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aramarketNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRs6efaAmYQgxvos2iT-12SJs5PyATI5k',
    appId: '1:613683440998:web:6dc52c7b47bdb89643aca7',
    messagingSenderId: '613683440998',
    projectId: 'fincom-dec4a',
    authDomain: 'fincom-dec4a.firebaseapp.com',
    storageBucket: 'fincom-dec4a.firebasestorage.app',
  );

}